export const MAX_ROUNDS = 6

export const SUPABASE_URL = 'https://agbofzcbkywbsojudbry.supabase.co'
export const SUPABASE_KEY =
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFnYm9memNia3l3YnNvanVkYnJ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MjMzNDQ0ODAsImV4cCI6MjAzODkyMDQ4MH0.WeYGvm00hGFeCJWQS-YWz-xm66OKq6Gu8zicRxoxYxg'
